### ISSUE TITLE
Not sure the delay setting is working.

### ISSUE THREAD

**Issue by Sacrilege** [deadlydog/AzureDevOps.WindowsScheduledTasks#3]
I'm creating a task using the inline option. I set the "Start Time Random Delay (in Minutes)" field to a value of 30. When I examine the scheduled task that was created/updated I expect to see the "Delay task for up to (random delay)" setting on the trigger advanced settings to be enabled and for the value to match "30 minutes". That's not the case though. This is true for both a new scheduled task being created an existing one being updated.

**Comment by deadlydog** [comment]
Thanks for reporting this issue @Sacrilege . Unfortunately my GitHub notifications weren't setup correctly and I never got a notification about this :( 

There was a bug with that field when setting the Scheduled Task settings using the `Inline` method that got fixed up in PR #7 . The bug should have been fixed in v2.0.17 of the extension. If you try it again now it should work as expected. If not, feel free to reopen this issue.

Thanks!
